name: PR Assignments
on:
  pull_request:
    types:
      - opened
jobs:
  assignments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.REQUEST_REVIEW_TOKEN }}
          script: |
            const script = require('./bin/pr-assignments.js');
            await script({github, context});
