name: PR Assignments
on:
  pull_request:
    types:
      - opened
jobs:
  assignments:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v6
        with:
          script: |
            const script = require('./bin/pr-assignments.js');
            await script({github, context});
