name: Update Release Window

concurrency:
  group: update-release-window
  cancel-in-progress: true
on:
  delete:
  create:
jobs:
  execute:
    name: Update Window Secret
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version-file: ".nvmrc"
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install deps
        run: npm ci
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.SECRETS_PAT }}
          script: |
            const sodium = require('libsodium-wrappers');
            const script = require('./bin/update-release-window.js');
            await script({github, context, sodium});
