name: Verify Release Branch
on:
  pull_request:
    types:
      - opened
      - edited
      - ready_for_review
jobs:
  verifyBranch:
    if: contains(github.event.pull_request.body, 'Release:')
    runs-on: ubuntu-latest
    env:
      BODY: ${{ github.event.pull_request.body }}
    steps:
      - uses: actions/checkout@v3
      - run: ./bin/verify-release-branch.sh
